### ISSUE TITLE
the web interface does not authenticate the zabbix server

### ISSUE THREAD

**Issue by janssenlima** [bhuisgen/zabbix-monitor#3]
The installation was successful. I can access the web interface of the zabbix-monitor, however, he complains of access credentials. But they are correct. Is there a log that I can review?

**Comment by bhuisgen** [comment]
Check in your brower JS console and if needed you can enable the debug flag to view API calls in the configuration file :
```
  development: {
    server: {
      url: 'https://zabbix.my.domain/api_jsonrpc.php',
      user: 'zabbix-monitor',
      password: 'secret123',
      options: {
        debug: true
      }
    },
```

**Comment by janssenlima** [comment]
It is presenting the following errors:
```
Uncaught ReferenceError: require is not defined(anonymous function) @ bec50b76.app.js:6
https://127.0.0.1/zabbix/api_jsonrpc.php Failed to load resource: net::ERR_CONNECTION_REFUSED
```
only works with https?

**Comment by bhuisgen** [comment]
Check if https://127.0.0.1/zabbix/api_jsonrpc.php is valid and if the browser doesn't warn/block for the SSL certificate.
